# E. Broadcasting

When dealing with Numpy arrays, there are times when you have to perform arithmetic operations on arrays of different shapes.

Let's assume there are two Numpy arrays you would perform an arithmetic operation on. One is of shape (4, 2), and the other one is of shape (2, &nbsp;). In this case, the operation must be performed in the way that the second array, <code>(2,&nbsp;)</code>, is used on every row of the first array.



<!-- ![image.png](attachment:image.png)
  (a) Column-wise block-striped and (b) row-wise block-striped decompositions of the matrix (Wittaya Chantamas and Johnnie Warren Baker 2010, p. 6)
 -->

In this section, we'll be discussing **Broadcasting** that enables arithmetic operations between arrays with different dimension




### _Objective_
1. Broadcasting: Understanding **Broadcasting** for arithmetic operations between arrays with different dimension

## 1. Broadcasting

The term **"broadcasting"** describes how numpy treats arrays with different shapes during arithmetic operations. The array with the less axes is considered a smaller array, and the other one is a larger array. Numpy expands the domain of operations over arrays by **adjusting the shape of the smaller array to that of the larger array** or **reshaping both arrays to the level of operation-compatible**.


Then, how does **broadcasting** happen? It consists of two steps.
1. axes are added to the smaller array to match the number of dimensions of the larger array until `smaller_array.ndim == larger_array.ndim`

2. The smaller array loops over these new axes to match the full shape of the larger array.

In [ ]:
import numpy as np

### (1) Broadcasting Examples

<Example 1> <br><img src='https://imgur.com/Q5DLh1m.jpg' align=left />

The above figure shows a 1-dimensional array  `[0, 1, 2]` and a scalar `5`.
During the operation, the scalar `5` acts as though it was converted to `[5, 5, 5]` of shape (3, &nbsp;), and the addition results in `[5, 6, 7]`.



In [ ]:
A = np.arange(3)
A

array([0, 1, 2])

In [ ]:
A + 5

array([5, 6, 7])

You can see the scalar 5 is added to every elements of `A`.

<Example 2> <br><img src='https://imgur.com/vRwGp0E.jpg' align=left />

The following example is a bit more complicated. It is an operation between a 1-dimensional array and a 2-dimensional array. The smaller array of shape (3,&nbsp; &nbsp;) is first converted to a 2-dimensional, of shape (1, 3) and adjusts the number of rows to 3, ultimately performing as a `(3, 3)-array` during the operation as below.   <br>
> `[[0, 1, 2],` <br>
&nbsp;&nbsp;`[0, 1, 2],` <br>
&nbsp;&nbsp;`[0, 1, 2]]` 

In [ ]:
A = np.ones((3,3))
print(A.shape)
A

(3, 3)


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
B = np.arange(3)
print(B.shape)
B

(3,)


array([0, 1, 2])

In [ ]:
A + B

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

You can see the smaller array `B` is broadcast across the larger array `A` during the operation.

<Example 3> <br><img src='https://imgur.com/Uy0BPLN.jpg' align=left />

The last example is adding `[[0], [1], [2]]` to  `[0,1,2]`.  

np.arange(3).reshape((3, 1)), (`[[0], [1], [2]]`), assigned to `A` is a 2-dimensional array of shape (3, 1).<br>
np.arange(3), `[0, 1, 2]`, assigned to `B` is a 1-dimensional array of shape(3,&nbsp; &nbsp;).

In [ ]:
A = np.arange(3).reshape((3,1))
B = np.arange(3)

In [ ]:
print(A.shape)
A

(3, 1)


array([[0],
       [1],
       [2]])

In [ ]:
print(B.shape)
B

(3,)


array([0, 1, 2])

In [ ]:
print('A.ndim', A.ndim)
print('B.ndim', B.ndim)

A.ndim 2
B.ndim 1


`A` and `B` are of different number of dimensions, rows and columns. How would the arrays be transformed then?

First, the array that needs to increase the number of dimensions pushes `elements per axis` value one by one to the right and add a new axis on the very left.
In other words, in the shape of the smaller array, (3,&nbsp; &nbsp;), 3 is pushed to the right past a comma, and a new axis is added to the left side, becoming a shape of (1,3).<br>

Now, since the two arrays are of the same number of dimensions but different number of rows and columns, they need to be reshaped to become operation-compatible, fitting the number of rows and columns to that of each other. Consequently, they act as **`arrays of shape (3, 3)`** during the operation.

In [ ]:
result = A + B
result

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [ ]:
result.shape

(3, 3)

### (2) Rules of Broadcasting

As you can see, Numpy enhances the efficiency of arithmetic operations between arrays of different shapes by **broadcasting**.

Though, broadcasting is helpful only if certain conditions on arrays are met, and here are some rules of Broadcasting.

- Rule 1. If two arrays for arithmetic operations are of different dimensions, add a new axis on the left of the smaller array by pushing `elements per axis` to the right.
> Example: Converting (3,&nbsp;&nbsp;) to (1,3)
<br>
- Rule 2. If the lengths of two 
arrays is neither the same on any axis nor is the length 1, broadcasting won't be working on these arrays.
> Example: If you try to add the arrays of shape `(2,3)` and `(3,2)` together, an error is returned.
<br><br>

- Rule 3. If two arrays do not have the same length on any axis but an axis of length 1, the array with the length of 1 expands to the length of another array on the corresponding axis.
> Example: Since the lengths of `A`, of shape (1, 3),and `B`, of (3, 1), do not match on any axis, both `A` and `B` expand to the shape (3, 3), axis = 0 of `A` becoming 3 as well as axis = 1 of `B` becoming 3.
 

You can visit the link below to find out more on Rules of Broadcasting 

**[Rules of Broadcasting](https://jakevdp.github.io/PythonDataScienceHandbook/02.05-computation-on-arrays-broadcasting.html#Rules-of-Broadcasting)**


We've already witnessed the validity of Rule 1 and 2, so let's take a look at how Rule 3 applies.

In [ ]:
A = np.arange(6)

In [ ]:
A.reshape(2,3) + A.reshape(3,2)

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

Since the lengths of two arrays are neither the same on any axis nor 1, it returns an error.