# F. Numpy Methods

So far, we've witnessed how Numpy lightens the burden of data handling in so many ways. On top of that, there is one more powerful feature of Numpy we haven't spoken about yet. In basic Python, it was said that you have to use either while or for loop to perform elementwise arithmetic operations on iterables. However, using Numpy allows you to do the same task only with a single functional set of code, and these single functional sets of code are called `universal functions` or `UFuncs`

So, in this section, we will be learning about `Universal Functions`.

### _Objective_
1. **Numpy Method** : Understanding how `universal functions` simplify operations on arrays.

In [1]:
import numpy as np

# \[1. Elementwise Operations\] 

You can perform the following types of elementwise operations with Numpy. 

1. Operations on array elements.
2. Operations between arrays of the same shape. 
3. Operations between arrays and scalars.
4. Operations between arrays of different shapes.
 

Let's see how the elementwise operations including the four basic arithmetic operations(+,-,*, /) are run on Numpy arrays.


## 1. Operations on Array Elements.

+ You can manipulate values in a Numpy array using the following Numpy methods.


Let's create a vector that contains values between 1(inclusive) and 5(exclusive) at the interval of 0.5. Then, get sine, exponential and logarithm of the given values. 

In [ ]:
A = np.arange(1,5,0.5)
A

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

### (1) `.sin()`
`.sin()` returns the sine of each element of the given array.

In [ ]:
np.sin(A)

array([ 0.84147098,  0.99749499,  0.90929743,  0.59847214,  0.14112001,
       -0.35078323, -0.7568025 , -0.97753012])

### (2) `.exp()`

`.exp()` returns the exponential of each element of the given array.

In [ ]:
np.exp(A)

array([ 2.71828183,  4.48168907,  7.3890561 , 12.18249396, 20.08553692,
       33.11545196, 54.59815003, 90.0171313 ])

### (3) `.log()`

`.log()` returns the logarithm of each element of the given array.

In [ ]:
np.log(A)

array([0.        , 0.40546511, 0.69314718, 0.91629073, 1.09861229,
       1.25276297, 1.38629436, 1.5040774 ])

### (4) `.matmul()`

`.matmul()` returns the matrix product of two given arrays. 

In [ ]:
W = np.array([
    [1,2,3],
    [2,3,4],
    [3,4,5]
])
X = np.array([
    [1],
    [2],
    [3],
])


In [ ]:
np.matmul(W,X)

array([[14],
       [20],
       [26]])

Let's have a look in more detail at how we came to this result.<br>
`1*1 + 2*2 + 3*3 = 14`<br>
`2*1 + 3*2 + 4*3 = 20`<br>
`3*1 + 4*2 + 5*3 = 26` <br>


# \[2. Aggregate Operations\]

Numpy provides a number of methods that perform aggregate operations along the specified axis. These methods return an array if an axis is specified to be removed, or a scalar otherwise.

#### Example Data)  mid-term and final report card of class 1. 

We will use the student report cards for the following examples. 

In [ ]:
midterm_scores = np.array([
    [80,92,70,65,92],
    [91,75,90,68,85],
    [86,76,42,72,88],
    [77,92,52,60,80],
    [75,85,85,92,95],
    [96,90,95,81,72]
])

final_scores = np.array([
    [85,95,90,66,93],
    [93,70,80,60,81],
    [89,78,55,75,80],
    [80,94,59,72,90],
    [70,82,81,95,72],
    [90,76,93,82,89]
])
final_scores.shape

(6, 5)

## 1. Numpy Methods for Aggregate Operations.

### (1) np.sum()
`.sum()` calculates the total sum of an array.

#### Total score in the midterm exam.

In [ ]:
midterm_scores.sum()

2399

#### Total score of student 0

In [ ]:
midterm_scores[0,:].sum()

399

### (2) np.mean()
`.mean()` calculates the average value of an array.

#### Average score in the midterm

In [ ]:
midterm_scores.mean()

79.96666666666667

#### Average score of student 4 in the midterm

In [ ]:
midterm_scores[4,:].mean()

86.4

### (3) np.max()
`.max()`returns the maximum value in an array.

 #### Top score in the final exam

In [ ]:
final_scores.max()

95

#### Highest score of student 2 in the final exam

In [ ]:
final_scores[2,:].max()

89

### (4) np.min()
`.min()`returns the minimum value in an array.

 #### Lowest score in the final exam 

In [ ]:
final_scores.min()

55

#### Lowest score of student 3 in the final exam

In [ ]:
final_scores[3,:].min()

59

### (5) np.std()
`.std()` returns the standard deviation, a measure of the spread of a distribution, of the array elements.

#### The standard deviation of scores in the midterm exam

In [ ]:
midterm_scores.std() 

13.011490648226621

### (6) np.stack()
`np.stack()` joins a sequence of arrays along a new axis. Note that the stacked array has one more dimension than before.

#### Joining midterm and final exam scores into a new array

In [ ]:
scores = np.stack([midterm_scores,final_scores])
print(scores.shape)
scores

(2, 6, 5)


array([[[80, 92, 70, 65, 92],
        [91, 75, 90, 68, 85],
        [86, 76, 42, 72, 88],
        [77, 92, 52, 60, 80],
        [75, 85, 85, 92, 95],
        [96, 90, 95, 81, 72]],

       [[85, 95, 90, 66, 93],
        [93, 70, 80, 60, 81],
        [89, 78, 55, 75, 80],
        [80, 94, 59, 72, 90],
        [70, 82, 81, 95, 72],
        [90, 76, 93, 82, 89]]])

The shape of the stacked array indicates

- 2 on axis = 0 : Exams (midterm, final)
- 6 on axis = 1 : Students (6 students in total)
- 5 on axis = 2 : Subjects (5 subjects)

### (7) np.all()
`.all()` tests whether or not all array elements alongside the given axis are true It returns 'True' if all elements are true, or 'False' otherwise.

#### Checking who scored 90 or higher in both English exams.

In order to apply `np.all()` based on the **exams**, we're going to set axis = 0 as an argument.

In [ ]:
np.all(scores[:,:,1]>=90, axis=0)

array([ True, False, False,  True, False, False])

Only student 0 and 4 scored 90 or higher in both English exams.

### (8) np.any()
`np.any` returns `True` if any array element on the given axis s true, and `False` otherwise.

When `np.any()` is used on two arrays, it proceeds an element-wise comparison of two arrays returning `True` if there is any matching pair.

#### Students with a score of 50 or less in both Math exams

Set `axis = 0` to see how students performed in both exams.

In [ ]:
np.any(scores[:,:,2]<=50, axis=0)

array([False, False,  True, False, False, False])

Student 2 scored 50 or less twice in a row.

### (9) np.unique()

`.unique()` returns the **unique elements** of an array. 

#### Finding the unique exam scores 

In [ ]:
np.unique(scores)

array([42, 52, 55, 59, 60, 65, 66, 68, 70, 72, 75, 76, 77, 78, 80, 81, 82,
       85, 86, 88, 89, 90, 91, 92, 93, 94, 95, 96])

In [ ]:
Only the unique exam scores are returned after duplicates.